[build-system]
requires = ["setuptools>=61"]
build-backend = "build_backend"
backend-path = ["."]

[project]
name = "trackio"
version = "0.1.0"
description = "attacker-controlled"
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
dev = []
spaces = []

[tool.setuptools]
packages = ["trackio_evil"]
